#!/usr/bin/env bash
[ -f "$HOME/.config/cronctl/enabled/forge-oracle" ] || exit 0
# ── The Oracle ──
# The human's ONE calm surface to look into the Forge. The vault is rich but can be
# noise; this is the lens that stays signal — a single screen, regenerated by the
# watchdog so it's always current. It points to detail (INDEX/LOG/MEMORY) rather than
# containing it. Curation rule: if a line wouldn't change a decision, it doesn't belong.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.env"
ORACLE="$VAULT/_ORACLE.md"
now=$(date -u '+%Y-%m-%d %H:%M UTC')

# refresh the signals we render from (NOT health.sh — it calls us; reading its last
# health.txt, <=15 min old, is fine). rollup.sh refreshes evaluate.txt internally.
bash "$SCRIPT_DIR/rollup.sh" >/dev/null 2>&1 || true

verdict=$(sed -n 's/^Forge health: \([A-Z_]*\).*/\1/p' "$HARNESS/state/health.txt" 2>/dev/null)
[[ -z "$verdict" ]] && verdict="UNKNOWN"
rate=$(sed -n '3p' "$HARNESS/state/evaluate.txt" 2>/dev/null | sed -nE 's/.*(Success rate.*)/\1/p')
counts=$(sed -n '2p' "$HARNESS/state/evaluate.txt" 2>/dev/null)
trend=$(bash "$SCRIPT_DIR/rollup.sh" trend 7 2>/dev/null)

pend=$(grep -c '^- \[ \]' "$QUEUE" 2>/dev/null)
quar_jobs=$(grep '^- \[!\] ' "$QUEUE" 2>/dev/null | sed 's/^- \[!\] //')
quar_n=$(printf '%s' "$quar_jobs" | grep -c . 2>/dev/null)

# NOTE: the old "Focus now" section echoed MEMORY.md's "Priority NOW" block. It was
# retired 2026-07-27 ([Janitor] ORACLE REFRESH): the curated _ORACLE-CURATED.md lead
# above now carries current focus + verdict, and the MEMORY echo had gone stale and
# contradicted it on the human's one screen. To restore: recompute `focus` from
# MEMORY.md "Priority NOW" and echo a "## Focus now" section below Pulse.

# recently forged value notes (newest first), session-digest noise excluded
recent=$(find "$VAULT/wiki" "$VAULT/projects" "$VAULT/.forge" -name '*.md' -type f \
  -printf '%T@\t%f\n' 2>/dev/null | sort -rn | head -5 | cut -f2 | sed 's/\.md$//')

case "$verdict" in
  HEALTHY) face="🟢";; CAPPED) face="🟦";; *) face="🔴";; esac

{
  echo "# 🔮 The Oracle"
  echo
  echo "> One glance at the Forge — curated, not complete. The richness lives behind the links; this is the lens. *Refreshed $now by the engine.*"
  echo
  # Curated verdict/arc lead — hand-maintained in _ORACLE-CURATED.md (a Janitor refreshes
  # it; this script only renders it). Leads the screen per the human's signal-not-noise
  # preference. Guarded: if the file is absent the Oracle still renders — the machinery
  # never depends on curated content existing. The file's <!-- ... --> doc comment is
  # stripped on inclusion.
  if [[ -f "$VAULT/_ORACLE-CURATED.md" ]]; then
    sed '/<!--/,/-->/d' "$VAULT/_ORACLE-CURATED.md"
    echo
  fi
  # FM-10 (W-2) gateway-flap alert: on an escalated 502-breaker hold (≥2 holds inside
  # GATEWAY_FLAP_WINDOW_S) the runner writes state/gateway_flap_alert ("<count> <first> <last>"
  # epochs) — the runner never writes the hand-maintained curated lead above, so this renders the
  # alert. ONE line while the marker exists and the window is live; the runner clears the marker on
  # recovery (a clean probe). A stale marker (last latch older than the window) never renders.
  if [[ -f "$HARNESS/state/gateway_flap_alert" ]]; then
    fa_n=""; fa_first=""; fa_last=""
    read -r fa_n fa_first fa_last < "$HARNESS/state/gateway_flap_alert" 2>/dev/null || true
    if [[ "$fa_n" =~ ^[0-9]+$ && "$fa_last" =~ ^[0-9]+$ ]] \
       && (( $(date -u +%s) - fa_last <= ${GATEWAY_FLAP_WINDOW_S:-21600} )); then
      echo "**⚠ Gateway flap:** ${fa_n} holds in $(( ${GATEWAY_FLAP_WINDOW_S:-21600} / 3600 ))h — upstream egress degraded, engine auto-holding (FM-7 surface, self-heals). GATEWAY_HOLD lines in LOG.md."
      echo
    fi
  fi
  echo "## $face Pulse — $verdict"
  echo "- **Today:** ${rate:-no sessions yet}"
  echo "- ${counts:-—}"
  echo "- **Queue:** $pend pending$( (( quar_n > 0 )) && echo " · $quar_n quarantined ⚠")"
  echo
  echo "## Trend (7 days)"
  echo '```'
  echo "${trend:-no data yet}"
  echo '```'
  echo
  echo "## Recently forged"
  printf '%s\n' "$recent" | sed 's/^/- [[/; s/$/]]/'
  echo
  if (( quar_n > 0 )); then
    echo "## ⚠ Needs attention"
    printf '%s\n' "$quar_jobs" | sed 's/^/- [!] /'
    echo
  fi
  echo "---"
  echo "Go deeper → [[INDEX]] (map) · LOG.md (audit) · [[MEMORY]] (working memory)"
} > "$ORACLE"

echo "oracle → $ORACLE"
